#!/bin/bash

rm -f ~/.bashrc ~/.inputrc ~/.bashprompt ~/.dircolors ~/.zshrc
ln -s .dotfiles/bashrc ~/.bashrc
ln -s .dotfiles/inputrc ~/.inputrc
ln -s .dotfiles/bashprompt ~/.bashprompt
ln -s .dotfiles/dircolors ~/.dircolors
ln -s .dotfiles/zshrc ~/.zshrc
