#!/bin/bash

function sha_to_branch_name
{
  sha=$1
  git name-rev --name-only $sha | tr '/' '-'
}

from=$(sha_to_branch_name $1)
to=$(sha_to_branch_name $2)
if [[ $3 == 1 && $from != $to ]]; then
  code_dir=$(git rev-parse --show-toplevel)
  tagfile=$(echo $code_dir-$to-tags | tr '/' '-' | cut -c2-)
  /usr/local/bin/ctags --recurse -f ~/.vim-tags/$tagfile $code_dir &
fi
